nelmio_cors:
    defaults:
        allow_origin: ["*"] # temporaire pour dev
        allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
    paths:
        "^/api/": ~
